#!/bin/bash

VAR_PWD=`pwd`

echo "Creating Blackberry Libraries"
source /Applications/bbndk/bbndk-env.sh
cd ../../src/tibb

make clean
make

cd $VAR_PWD

echo "Creating the BlackBerry drop-in folder at /build/sdk/blackberry"
node create_sdk.js

