#!/bin/bash

VAR_PWD=`pwd`

# Check OS
OS=$(uname -s)

BB_PATH="/Applications"

# Set bbndk path
if [ "$OS" == 'Linux' ]; then
    BB_PATH="/opt"
fi

echo "Creating Blackberry Libraries"
source $BB_PATH/bbndk/bbndk-env.sh
cd ../../src/tibb

make clean
make

cd $VAR_PWD

echo "Creating the BlackBerry drop-in folder at /build/sdk/blackberry"
node create_sdk.js

