#! /bin/sh

# Configure for your environment before running this script.
TI_SDK="/tmp/mobilesdk/osx/2.2.0" # Path to the Titanium SDK.
BBNDK="/Applications/bbndk"       # Path to the BlackBerry NDK.
DEVICE_IP="169.254.0.1"           # IP address of device.
DEVICE_PASS="pass"                # Device password
DEBUG_TOKEN=$HOME/debugtoken1.bar # Path to your debug token you uploaded to device.

$TI_SDK/blackberry/builder.py run -d $PWD -p $BBNDK -i $DEVICE_IP -s $DEVICE_PASS -t device --debug_token=$DEBUG_TOKEN
